name: NPM Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Build Package
        run: |
          npm install -g yarn
          yarn install
      - name: Register Token
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > /home/runner/work/_temp/.npmrc
          echo "_auth=$NPM_AUTH_TOKEN" >>  /home/runner/work/_temp/.npmrc
          echo "email=<dyzplus@gmail.com>" >>  /home/runner/work/_temp/.npmrc
          echo "always-auth=true" >>  /home/runner/work/_temp/.npmrc
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish
        run: npm publish
